name: Auto Build and Release

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    # =========================================
    # Checkout Repository
    # =========================================
    - name: Checkout
      uses: actions/checkout@v4

    # =========================================
    # Configure CMake
    # =========================================
    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    # =========================================
    # Build Project
    # =========================================
    - name: Build
      run: cmake --build build --config Release

    # =========================================
    # Create Release Folder
    # =========================================
    - name: Prepare Release Package
      shell: pwsh
      run: |
        mkdir release
        mkdir release/include
        mkdir release/bin

        Copy-Item -Recurse "include/BMP" "release/include/"
        Copy-Item "build/Release/BMP.dll" "release/bin/"
        Copy-Item "build/Release/BMP.lib" "release/bin/"

        $commit = "${{ github.sha }}".Substring(0,7)

        Compress-Archive `
          -Path "release/*" `
          -DestinationPath "BMP_Library_$commit.zip"

    # =========================================
    # Upload Build Artifact
    # =========================================
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: BMP-Library
        path: "*.zip"

    # =========================================
    # Delete Old Latest Release
    # =========================================
    - name: Delete Old Latest Release
      uses: dev-drprasad/delete-tag-and-release@v1.1
      with:
        delete_release: true
        tag_name: latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true

    # =========================================
    # Create Latest Tag
    # =========================================
    - name: Create Latest Tag
      run: |
        git tag latest
        git push origin latest --force

    # =========================================
    # Publish GitHub Release
    # =========================================
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        name: Latest Build
        body: |
          Automatic build generated from latest commit.

          Commit:
          ${{ github.sha }}

        files: "*.zip"

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
